fw = open("s.txt","w")
fw.write("hello\n")
fw.close()
fr = open("s.txt","r")
print(fr.read())
fr.close()
fa = open("s.txt","a")
fa.write("world")
fa.close()
ft = open("s.txt","r")
print(ft.tell())
print(ft.read(7))
print(ft.tell())
ft.close()